// Blog posts data for Photobooth Canada
export const blogPosts = [
  {
    id: 1,
    slug: 'wedding-photo-booth-ideas-2025',
    title: 'Top 10 Wedding Photo Booth Ideas for 2025',
    excerpt: 'Discover the latest wedding photo booth trends that will make your special day unforgettable. From elegant backdrops to interactive props.',
    category: 'Weddings',
    date: '2025-11-01',
    author: 'Photobooth Canada',
    readTime: '8 min read',
    image: '/eventgallery/1PBC.jpg',
    featured: true
  },
  {
    id: 2,
    slug: 'corporate-event-photo-booth-guide',
    title: 'The Ultimate Guide to Corporate Event Photo Booths',
    excerpt: 'Learn how photo booths can elevate your corporate events, boost engagement, and create lasting brand impressions.',
    category: 'Corporate',
    date: '2025-10-28',
    author: 'Photobooth Canada',
    readTime: '10 min read',
    image: '/eventgallery/2PBC.jpg',
    featured: true
  },
  {
    id: 3,
    slug: 'birthday-party-photo-booth-toronto',
    title: 'Birthday Party Photo Booth Ideas in Toronto',
    excerpt: 'Make your Toronto birthday celebration memorable with these creative photo booth ideas and themes.',
    category: 'Birthdays',
    date: '2025-10-25',
    author: 'Photobooth Canada',
    readTime: '6 min read',
    image: '/eventgallery/3PBC.jpg',
    featured: false
  },
  {
    id: 4,
    slug: '360-photo-booth-vs-traditional',
    title: '360 Photo Booth vs Traditional: Which is Right for Your Event?',
    excerpt: 'Compare 360 photo booths and traditional setups to find the perfect fit for your event needs.',
    category: 'Tips & Guides',
    date: '2025-10-22',
    author: 'Photobooth Canada',
    readTime: '7 min read',
    image: '/eventgallery/4PBC.jpg',
    featured: true
  },
  {
    id: 5,
    slug: 'graduation-photo-booth-ideas',
    title: '15 Creative Graduation Photo Booth Ideas',
    excerpt: 'Celebrate academic achievements with these fun and memorable graduation photo booth concepts.',
    category: 'Graduations',
    date: '2025-10-20',
    author: 'Photobooth Canada',
    readTime: '6 min read',
    image: '/eventgallery/5PBC.jpg',
    featured: false
  },
  {
    id: 6,
    slug: 'photo-booth-props-diy-guide',
    title: 'DIY Photo Booth Props: A Complete Guide',
    excerpt: 'Create amazing custom photo booth props for your event with our step-by-step guide.',
    category: 'DIY & Tips',
    date: '2025-10-18',
    author: 'Photobooth Canada',
    readTime: '9 min read',
    image: '/eventgallery/6PBC.jpg',
    featured: false
  },
  {
    id: 7,
    slug: 'winter-wedding-photo-booth-mississauga',
    title: 'Winter Wedding Photo Booth Ideas in Mississauga',
    excerpt: 'Discover enchanting winter-themed photo booth ideas perfect for Mississauga winter weddings.',
    category: 'Weddings',
    date: '2025-10-15',
    author: 'Photobooth Canada',
    readTime: '7 min read',
    image: '/eventgallery/7PBC.jpg',
    featured: false
  },
  {
    id: 8,
    slug: 'mirror-booth-vs-open-air',
    title: 'Mirror Booth vs Open Air: Making the Right Choice',
    excerpt: 'Explore the differences between mirror booths and open air setups for your event.',
    category: 'Tips & Guides',
    date: '2025-10-12',
    author: 'Photobooth Canada',
    readTime: '8 min read',
    image: '/eventgallery/8PBC.jpg',
    featured: false
  },
  {
    id: 9,
    slug: 'holiday-party-photo-booth-ideas',
    title: 'Holiday Party Photo Booth Ideas That Wow',
    excerpt: 'Transform your holiday party with these festive photo booth themes and decoration ideas.',
    category: 'Holidays',
    date: '2025-10-10',
    author: 'Photobooth Canada',
    readTime: '6 min read',
    image: '/eventgallery/9PBC.jpg',
    featured: false
  },
  {
    id: 10,
    slug: 'photo-booth-rental-cost-guide-ontario',
    title: 'Photo Booth Rental Cost Guide for Ontario Events',
    excerpt: 'Understand photo booth rental pricing and what factors affect the cost in Ontario.',
    category: 'Planning',
    date: '2025-10-08',
    author: 'Photobooth Canada',
    readTime: '10 min read',
    image: '/eventgallery/10PBC.jpg',
    featured: false
  },
  {
    id: 11,
    slug: 'baby-shower-photo-booth-themes',
    title: '12 Adorable Baby Shower Photo Booth Themes',
    excerpt: 'Celebrate the mom-to-be with these charming baby shower photo booth theme ideas.',
    category: 'Baby Showers',
    date: '2025-10-05',
    author: 'Photobooth Canada',
    readTime: '7 min read',
    image: '/eventgallery/11PBC.jpg',
    featured: false
  },
  {
    id: 12,
    slug: 'corporate-branding-photo-booth',
    title: 'How to Brand Your Corporate Photo Booth Experience',
    excerpt: 'Maximize brand visibility with strategic photo booth branding at corporate events.',
    category: 'Corporate',
    date: '2025-10-03',
    author: 'Photobooth Canada',
    readTime: '8 min read',
    image: '/eventgallery/12PBC.jpg',
    featured: false
  },
  {
    id: 13,
    slug: 'outdoor-photo-booth-setup-tips',
    title: 'Outdoor Photo Booth Setup: Essential Tips',
    excerpt: 'Learn how to successfully set up and run a photo booth at outdoor events.',
    category: 'Tips & Guides',
    date: '2025-10-01',
    author: 'Photobooth Canada',
    readTime: '9 min read',
    image: '/eventgallery/13PBC.jpg',
    featured: false
  },
  {
    id: 14,
    slug: 'prom-photo-booth-ideas-2025',
    title: 'Prom Photo Booth Ideas for 2025',
    excerpt: 'Make prom night unforgettable with these trendy photo booth ideas and themes.',
    category: 'School Events',
    date: '2025-09-28',
    author: 'Photobooth Canada',
    readTime: '6 min read',
    image: '/eventgallery/14PBC.jpg',
    featured: false
  },
  {
    id: 15,
    slug: 'photo-booth-backdrops-guide',
    title: 'The Complete Guide to Photo Booth Backdrops',
    excerpt: 'Choose the perfect backdrop for your photo booth with our comprehensive guide.',
    category: 'DIY & Tips',
    date: '2025-09-25',
    author: 'Photobooth Canada',
    readTime: '10 min read',
    image: '/eventgallery/15PBC.jpg',
    featured: false
  },
  {
    id: 16,
    slug: 'charity-fundraiser-photo-booth',
    title: 'Using Photo Booths to Boost Charity Fundraisers',
    excerpt: 'Discover how photo booths can increase engagement and donations at fundraising events.',
    category: 'Fundraisers',
    date: '2025-09-22',
    author: 'Photobooth Canada',
    readTime: '7 min read',
    image: '/eventgallery/16PBC.jpg',
    featured: false
  },
  {
    id: 17,
    slug: 'wedding-reception-photo-booth-brampton',
    title: 'Wedding Reception Photo Booth Ideas in Brampton',
    excerpt: 'Explore popular wedding photo booth trends for Brampton receptions.',
    category: 'Weddings',
    date: '2025-09-20',
    author: 'Photobooth Canada',
    readTime: '8 min read',
    image: '/eventgallery/17PBC.jpg',
    featured: false
  },
  {
    id: 18,
    slug: 'instant-print-vs-digital-photo-booth',
    title: 'Instant Print vs Digital Photo Booths: Pros and Cons',
    excerpt: 'Compare instant print and digital-only photo booth options for your event.',
    category: 'Tips & Guides',
    date: '2025-09-18',
    author: 'Photobooth Canada',
    readTime: '7 min read',
    image: '/eventgallery/18PBC.jpg',
    featured: false
  },
  {
    id: 19,
    slug: 'sweet-16-photo-booth-ideas',
    title: 'Sweet 16 Photo Booth Ideas to Remember',
    excerpt: 'Create an unforgettable Sweet 16 celebration with these photo booth concepts.',
    category: 'Birthdays',
    date: '2025-09-15',
    author: 'Photobooth Canada',
    readTime: '6 min read',
    image: '/eventgallery/19PBC.jpg',
    featured: false
  },
  {
    id: 20,
    slug: 'photo-booth-lighting-tips',
    title: 'Photo Booth Lighting: A Professional Guide',
    excerpt: 'Master photo booth lighting techniques for stunning event photos.',
    category: 'Tips & Guides',
    date: '2025-09-12',
    author: 'Photobooth Canada',
    readTime: '9 min read',
    image: '/eventgallery/20PBC.jpg',
    featured: false
  },
  {
    id: 21,
    slug: 'conference-photo-booth-engagement',
    title: 'Maximizing Conference Engagement with Photo Booths',
    excerpt: 'Learn how photo booths drive attendee engagement at conferences and trade shows.',
    category: 'Corporate',
    date: '2025-09-10',
    author: 'Photobooth Canada',
    readTime: '8 min read',
    image: '/eventgallery/21PBC.jpg',
    featured: false
  },
  {
    id: 22,
    slug: 'halloween-party-photo-booth',
    title: 'Spooky Halloween Party Photo Booth Ideas',
    excerpt: 'Get inspired with these creative Halloween-themed photo booth setups.',
    category: 'Holidays',
    date: '2025-09-08',
    author: 'Photobooth Canada',
    readTime: '7 min read',
    image: '/eventgallery/22PBC.jpg',
    featured: false
  },
  {
    id: 23,
    slug: 'engagement-party-photo-booth-markham',
    title: 'Engagement Party Photo Booth Ideas in Markham',
    excerpt: 'Celebrate your engagement with these romantic photo booth ideas in Markham.',
    category: 'Engagements',
    date: '2025-09-05',
    author: 'Photobooth Canada',
    readTime: '6 min read',
    image: '/eventgallery/23PBC.jpg',
    featured: false
  },
  {
    id: 24,
    slug: 'photo-booth-social-media-integration',
    title: 'Photo Booth Social Media Integration Guide',
    excerpt: 'Boost your event\'s social media presence with integrated photo booth sharing.',
    category: 'Tips & Guides',
    date: '2025-09-03',
    author: 'Photobooth Canada',
    readTime: '8 min read',
    image: '/eventgallery/24PBC.jpg',
    featured: false
  },
  {
    id: 25,
    slug: 'bar-mitzvah-photo-booth-ideas',
    title: 'Bar & Bat Mitzvah Photo Booth Ideas',
    excerpt: 'Make this milestone celebration special with creative photo booth themes.',
    category: 'Celebrations',
    date: '2025-09-01',
    author: 'Photobooth Canada',
    readTime: '7 min read',
    image: '/eventgallery/25PBC.jpg',
    featured: false
  },
  {
    id: 26,
    slug: 'photo-booth-guest-book-alternative',
    title: 'Photo Booth Guest Books: A Modern Alternative',
    excerpt: 'Replace traditional guest books with interactive photo booth alternatives.',
    category: 'Weddings',
    date: '2025-08-29',
    author: 'Photobooth Canada',
    readTime: '6 min read',
    image: '/eventgallery/26PBC.jpg',
    featured: false
  },
  {
    id: 27,
    slug: 'summer-wedding-photo-booth-vaughan',
    title: 'Summer Wedding Photo Booth Ideas in Vaughan',
    excerpt: 'Discover fresh summer wedding photo booth concepts for Vaughan venues.',
    category: 'Weddings',
    date: '2025-08-26',
    author: 'Photobooth Canada',
    readTime: '8 min read',
    image: '/eventgallery/27PBC.jpg',
    featured: false
  },
  {
    id: 28,
    slug: 'photo-booth-for-small-events',
    title: 'Photo Booth Solutions for Small Intimate Events',
    excerpt: 'Find the perfect photo booth setup for smaller gatherings and intimate celebrations.',
    category: 'Planning',
    date: '2025-08-24',
    author: 'Photobooth Canada',
    readTime: '7 min read',
    image: '/eventgallery/28PBC.jpg',
    featured: false
  },
  {
    id: 29,
    slug: 'new-years-eve-photo-booth',
    title: 'New Year\'s Eve Photo Booth Ideas',
    excerpt: 'Ring in the new year with these glamorous photo booth themes and props.',
    category: 'Holidays',
    date: '2025-08-22',
    author: 'Photobooth Canada',
    readTime: '6 min read',
    image: '/eventgallery/29PBC.jpg',
    featured: false
  },
  {
    id: 30,
    slug: 'photo-booth-rental-checklist',
    title: 'Complete Photo Booth Rental Checklist',
    excerpt: 'Everything you need to know before booking a photo booth for your event.',
    category: 'Planning',
    date: '2025-08-20',
    author: 'Photobooth Canada',
    readTime: '10 min read',
    image: '/eventgallery/30PBC.jpg',
    featured: false
  },
  {
    id: 31,
    slug: 'retirement-party-photo-booth',
    title: 'Retirement Party Photo Booth Ideas',
    excerpt: 'Celebrate career milestones with memorable retirement party photo booth themes.',
    category: 'Corporate',
    date: '2025-08-18',
    author: 'Photobooth Canada',
    readTime: '7 min read',
    image: '/eventgallery/1PBC.jpg',
    featured: false
  },
  {
    id: 32,
    slug: 'photo-booth-for-kids-parties',
    title: 'Kid-Friendly Photo Booth Ideas for Children\'s Parties',
    excerpt: 'Create a fun and safe photo booth experience for kids\' birthday parties.',
    category: 'Birthdays',
    date: '2025-08-15',
    author: 'Photobooth Canada',
    readTime: '8 min read',
    image: '/eventgallery/2PBC.jpg',
    featured: false
  },
  {
    id: 33,
    slug: 'anniversary-photo-booth-richmond-hill',
    title: 'Anniversary Celebration Photo Booth in Richmond Hill',
    excerpt: 'Mark your milestone anniversary with a photo booth in Richmond Hill.',
    category: 'Anniversaries',
    date: '2025-08-12',
    author: 'Photobooth Canada',
    readTime: '6 min read',
    image: '/eventgallery/3PBC.jpg',
    featured: false
  },
  {
    id: 34,
    slug: 'green-screen-photo-booth-guide',
    title: 'Green Screen Photo Booths: The Ultimate Guide',
    excerpt: 'Explore the possibilities of green screen technology in photo booths.',
    category: 'Tips & Guides',
    date: '2025-08-10',
    author: 'Photobooth Canada',
    readTime: '9 min read',
    image: '/eventgallery/4PBC.jpg',
    featured: false
  },
  {
    id: 35,
    slug: 'spring-wedding-photo-booth-ideas',
    title: 'Spring Wedding Photo Booth Ideas',
    excerpt: 'Embrace the season with these fresh spring wedding photo booth concepts.',
    category: 'Weddings',
    date: '2025-08-08',
    author: 'Photobooth Canada',
    readTime: '7 min read',
    image: '/eventgallery/5PBC.jpg',
    featured: false
  },
  {
    id: 36,
    slug: 'photo-booth-data-collection',
    title: 'Using Photo Booths for Event Data Collection',
    excerpt: 'Learn how to leverage photo booths for valuable event attendee data.',
    category: 'Corporate',
    date: '2025-08-05',
    author: 'Photobooth Canada',
    readTime: '8 min read',
    image: '/eventgallery/6PBC.jpg',
    featured: false
  },
  {
    id: 37,
    slug: 'quinceanera-photo-booth-ideas',
    title: 'Quinceañera Photo Booth Ideas and Themes',
    excerpt: 'Celebrate this special milestone with beautiful quinceañera photo booth setups.',
    category: 'Celebrations',
    date: '2025-08-03',
    author: 'Photobooth Canada',
    readTime: '7 min read',
    image: '/eventgallery/7PBC.jpg',
    featured: false
  },
  {
    id: 38,
    slug: 'photo-booth-attendant-importance',
    title: 'Why a Photo Booth Attendant Matters',
    excerpt: 'Discover the value of having a professional attendant at your photo booth.',
    category: 'Tips & Guides',
    date: '2025-08-01',
    author: 'Photobooth Canada',
    readTime: '6 min read',
    image: '/eventgallery/8PBC.jpg',
    featured: false
  },
  {
    id: 39,
    slug: 'office-party-photo-booth-oakville',
    title: 'Office Party Photo Booth Ideas in Oakville',
    excerpt: 'Boost team morale with fun office party photo booth experiences in Oakville.',
    category: 'Corporate',
    date: '2025-07-29',
    author: 'Photobooth Canada',
    readTime: '7 min read',
    image: '/eventgallery/9PBC.jpg',
    featured: false
  },
  {
    id: 40,
    slug: 'photo-booth-gif-vs-boomerang',
    title: 'Photo Booth GIFs vs Boomerangs: Which is Better?',
    excerpt: 'Compare GIF and Boomerang features for your event photo booth.',
    category: 'Tips & Guides',
    date: '2025-07-26',
    author: 'Photobooth Canada',
    readTime: '6 min read',
    image: '/eventgallery/10PBC.jpg',
    featured: false
  },
  {
    id: 41,
    slug: 'gender-reveal-photo-booth',
    title: 'Gender Reveal Party Photo Booth Ideas',
    excerpt: 'Capture the excitement of your gender reveal with these photo booth themes.',
    category: 'Baby Showers',
    date: '2025-07-24',
    author: 'Photobooth Canada',
    readTime: '6 min read',
    image: '/eventgallery/11PBC.jpg',
    featured: false
  },
  {
    id: 42,
    slug: 'photo-booth-for-virtual-events',
    title: 'Virtual Photo Booth Solutions for Hybrid Events',
    excerpt: 'Extend your photo booth experience to virtual and hybrid event attendees.',
    category: 'Corporate',
    date: '2025-07-22',
    author: 'Photobooth Canada',
    readTime: '8 min read',
    image: '/eventgallery/12PBC.jpg',
    featured: false
  },
  {
    id: 43,
    slug: 'rustic-wedding-photo-booth-hamilton',
    title: 'Rustic Wedding Photo Booth Ideas in Hamilton',
    excerpt: 'Create a charming rustic photo booth experience for Hamilton weddings.',
    category: 'Weddings',
    date: '2025-07-20',
    author: 'Photobooth Canada',
    readTime: '7 min read',
    image: '/eventgallery/13PBC.jpg',
    featured: false
  },
  {
    id: 44,
    slug: 'photo-booth-print-layouts',
    title: 'Creative Photo Booth Print Layout Ideas',
    excerpt: 'Design memorable photo booth prints with these layout inspirations.',
    category: 'DIY & Tips',
    date: '2025-07-18',
    author: 'Photobooth Canada',
    readTime: '9 min read',
    image: '/eventgallery/14PBC.jpg',
    featured: false
  },
  {
    id: 45,
    slug: 'college-event-photo-booth',
    title: 'Photo Booth Ideas for College Events',
    excerpt: 'Engage students with creative photo booth setups at campus events.',
    category: 'School Events',
    date: '2025-07-15',
    author: 'Photobooth Canada',
    readTime: '7 min read',
    image: '/eventgallery/15PBC.jpg',
    featured: false
  },
  {
    id: 46,
    slug: 'photo-booth-slow-motion-video',
    title: 'Slow Motion Video Booths: The Next Big Thing',
    excerpt: 'Discover the trend of slow-motion video booths for events.',
    category: 'Tips & Guides',
    date: '2025-07-12',
    author: 'Photobooth Canada',
    readTime: '8 min read',
    image: '/eventgallery/16PBC.jpg',
    featured: false
  },
  {
    id: 47,
    slug: 'product-launch-photo-booth',
    title: 'Photo Booths for Product Launch Events',
    excerpt: 'Create buzz and engagement at product launches with strategic photo booth placement.',
    category: 'Corporate',
    date: '2025-07-10',
    author: 'Photobooth Canada',
    readTime: '8 min read',
    image: '/eventgallery/17PBC.jpg',
    featured: false
  },
  {
    id: 48,
    slug: 'destination-wedding-photo-booth',
    title: 'Photo Booth Tips for Destination Weddings',
    excerpt: 'Plan the perfect photo booth experience for your destination wedding.',
    category: 'Weddings',
    date: '2025-07-08',
    author: 'Photobooth Canada',
    readTime: '9 min read',
    image: '/eventgallery/18PBC.jpg',
    featured: false
  },
  {
    id: 49,
    slug: 'photo-booth-accessibility-guide',
    title: 'Making Photo Booths Accessible for All Guests',
    excerpt: 'Ensure your photo booth is inclusive and accessible to guests with disabilities.',
    category: 'Tips & Guides',
    date: '2025-07-05',
    author: 'Photobooth Canada',
    readTime: '7 min read',
    image: '/eventgallery/19PBC.jpg',
    featured: false
  },
  {
    id: 50,
    slug: 'photo-booth-trends-2025',
    title: 'Photo Booth Trends to Watch in 2025',
    excerpt: 'Stay ahead with these emerging photo booth trends for the coming year.',
    category: 'Trends',
    date: '2025-07-03',
    author: 'Photobooth Canada',
    readTime: '10 min read',
    image: '/eventgallery/20PBC.jpg',
    featured: true
  },
  {
    id: 51,
    slug: 'photobooth-canada-sponsors-tedxuoft-2025',
    title: 'Photobooth Canada Proudly Sponsors TEDxUofT 2025',
    excerpt: 'We are thrilled to announce our sponsorship of TEDxUofT 2025, bringing innovative photo booth experiences to one of Toronto\'s most inspiring events.',
    category: 'Corporate',
    date: '2025-11-21',
    author: 'Photobooth Canada Team',
    readTime: '5 min read',
    image: '/eventgallery/tedx-background.jpg',
    featured: true
  },
  {
    id: 52,
    slug: 'photo-booth-trends-canada-2026',
    title: 'Photo Booth Trends in Canada for 2026 (What Events Are Booking Now)',
    excerpt: 'Discover the hottest photo booth trends taking over Canadian events in 2026, from custom keepsakes to sports card prints.',
    category: 'Trends',
    date: '2025-12-30',
    author: 'Photobooth Canada',
    readTime: '12 min read',
    image: '/eventgallery1/1.png',
    featured: true
  },
  {
    id: 53,
    slug: 'keychain-photo-booth-favors-replacing-prints',
    title: 'Keychain Photo Booth Favors: Why Events Are Replacing Paper Prints',
    excerpt: 'Learn why keychain photo booth favors are becoming the preferred choice over traditional paper prints for lasting memories.',
    category: 'Tips & Guides',
    date: '2025-12-29',
    author: 'Photobooth Canada',
    readTime: '10 min read',
    image: '/eventgallery1/2.png',
    featured: true
  },
  {
    id: 54,
    slug: 'photo-booth-magnets-vs-prints-guest-memory',
    title: 'Photo Booth Magnets vs Prints: Which Keeps Guests Remembering Your Event?',
    excerpt: 'Compare photo booth magnets and prints to discover which creates lasting memories and better brand recall for your event.',
    category: 'Tips & Guides',
    date: '2025-12-28',
    author: 'Photobooth Canada',
    readTime: '9 min read',
    image: '/eventgallery1/3.png',
    featured: true
  },
  {
    id: 55,
    slug: 'sports-card-photo-booths-interactive-experience',
    title: 'Sports Card Photo Booths: The Hottest Interactive Experience for Sports & School Events',
    excerpt: 'Discover how sports card photo booths are revolutionizing school tournaments, team banquets, and corporate sports events.',
    category: 'School Events',
    date: '2025-12-27',
    author: 'Photobooth Canada',
    readTime: '11 min read',
    image: '/eventgallery1/4.png',
    featured: true
  },
  {
    id: 56,
    slug: 'custom-photo-booth-layouts-guest-engagement',
    title: 'Custom Photo Booth Layouts: How Design Impacts Guest Engagement',
    excerpt: 'Learn how strategic photo booth layout design can dramatically increase guest participation and event satisfaction.',
    category: 'Tips & Guides',
    date: '2025-12-26',
    author: 'Photobooth Canada',
    readTime: '10 min read',
    image: '/eventgallery1/5.png',
    featured: true
  },
  {
    id: 57,
    slug: 'corporate-photo-booth-rentals-canada-branding-converts',
    title: 'Corporate Photo Booth Rentals in Canada: Branding That Actually Converts',
    excerpt: 'Discover how corporate photo booth rentals with strategic branding generate leads and ROI at Canadian business events.',
    category: 'Corporate',
    date: '2025-12-25',
    author: 'Photobooth Canada',
    readTime: '13 min read',
    image: '/eventgallery1/6.png',
    featured: true
  },
  {
    id: 58,
    slug: 'wedding-photo-booth-ideas-canadians-love-keepsakes',
    title: 'Wedding Photo Booth Ideas Canadians Love (From Magnets to Keepsakes)',
    excerpt: 'Explore the most popular wedding photo booth trends across Canada, featuring physical keepsakes that guests actually treasure.',
    category: 'Weddings',
    date: '2025-12-24',
    author: 'Photobooth Canada',
    readTime: '11 min read',
    image: '/eventgallery1/7.png',
    featured: true
  },
  {
    id: 59,
    slug: 'are-photo-booths-worth-it-2026-guest-expectations',
    title: 'Are Photo Booths Still Worth It in 2026? Here\'s What Guests Actually Want',
    excerpt: 'Get the honest answer about photo booth value in 2026, including what modern guests expect from their event experience.',
    category: 'Tips & Guides',
    date: '2025-12-23',
    author: 'Photobooth Canada',
    readTime: '9 min read',
    image: '/eventgallery1/8.png',
    featured: true
  },
  {
    id: 60,
    slug: 'photo-booth-keepsakes-increase-brand-recall-events',
    title: 'How Photo Booth Keepsakes Increase Brand Recall After Events',
    excerpt: 'Discover the psychology behind photo booth keepsakes and how magnets and keychains outperform traditional corporate swag.',
    category: 'Corporate',
    date: '2025-12-22',
    author: 'Photobooth Canada',
    readTime: '10 min read',
    image: '/eventgallery1/9.png',
    featured: true
  },
  {
    id: 61,
    slug: 'choosing-right-photo-booth-package-event-canada',
    title: 'Choosing the Right Photo Booth Package for Your Event in Canada',
    excerpt: 'Complete guide to selecting the perfect photo booth package for your Canadian event, including budget tiers and customization options.',
    category: 'Planning',
    date: '2025-12-21',
    author: 'Photobooth Canada',
    readTime: '14 min read',
    image: '/eventgallery1/10.png',
    featured: true
  },
  {
    id: 62,
    slug: 'luxury-photo-booth-backdrops-canada-premium-events',
    title: 'Luxury Photo Booth Backdrops in Canada: Elevating Premium Events',
    excerpt: 'Discover how luxury photo booth backdrops transform Canadian events, from royal sapphire elegance to golden radiance collections.',
    category: 'Tips & Guides',
    date: '2025-12-30',
    author: 'Photobooth Canada',
    readTime: '11 min read',
    image: '/eventgallery1/11.png',
    featured: true
  },
  {
    id: 63,
    slug: 'choosing-perfect-backdrop-color-event-psychology',
    title: 'Choosing the Perfect Backdrop Color for Your Event: The Psychology Behind Luxury Backdrops',
    excerpt: 'Learn how backdrop colors influence guest emotions and event success, with expert insights on luxury backdrop selection.',
    category: 'Tips & Guides',
    date: '2025-12-30',
    author: 'Photobooth Canada',
    readTime: '10 min read',
    image: '/eventgallery1/12.png',
    featured: true
  }
];

export const blogCategories = [
  'All',
  'Weddings',
  'Corporate',
  'Birthdays',
  'Tips & Guides',
  'Graduations',
  'Holidays',
  'Planning',
  'DIY & Tips',
  'School Events',
  'Fundraisers',
  'Celebrations',
  'Trends'
];
